"""Apply runtime cash/holdings models to owned source records; publish no amounts."""

from auto_invest.broker.intraday_cash_baseline import (
    CURRENT,
    MARGIN,
    normalize_cash_baseline,
    normalize_usd_settlement_cash,
)
from auto_invest.broker.intraday_holdings_coverage import (
    compare_current_holdings,
    normalize_current_holdings,
)
from auto_invest.broker.intraday_reported_cash import normalize_reported_cash


def assess_account_models(responses, ordinary, domestic, *, observed_at):
    """Inputs belong to one AccountHistory collection, never an operator JSON file."""
    selected = ([row for row in responses if isinstance(row, dict)
                 and row.get("endpoint") in {CURRENT, MARGIN}]
                if isinstance(responses, list) and len(responses) <= 200 else [])
    baseline = normalize_cash_baseline(selected, observed_at=observed_at)
    settlement = normalize_usd_settlement_cash(selected, observed_at=observed_at)
    baseline["settlement_cash"] = settlement
    holdings = normalize_current_holdings(selected, observed_at=observed_at)
    cash = normalize_reported_cash(baseline, domestic, observed_at=observed_at)
    coverage = compare_current_holdings(holdings, ordinary, observed_at=observed_at)

    def public(result):
        # Each value is generated by these models from a fixed local vocabulary.
        # Explicit projection keeps newly added private fields private by default.
        return {key: result[key] for key in (
            "status", "reason", "scope", "usd_margin_row_count", "positive_holding_count",
            "equity_holdings_matched",
        ) if key in result}

    return dict(schema_version=1, zero_adjustment_cash=public(baseline),
                reported_settlement_cash=public(settlement), reported_cash_valuation=public(cash),
                current_holdings=public(holdings), holdings_coverage=public(coverage),
                full_account_scope_verified=False, cash_aggregation_verified=False,
                nav_verified=False, live_eligible=False, additional_requests=0)
